### ISSUE TITLE
能否加上搜索建议？就是输入关键词智能关联

### ISSUE THREAD

**Issue by dinphy** [virzs/Search#1]
就像这个页面这种
[http://www.doradorami.cn/daohang/](http://www.doradorami.cn/daohang/)

**Comment by virzs** [comment]
这个是可以的，main.js中最下面废弃代码中保留有搜索建议，不过只有百度的，取消注释就可以正常显示，没有添加样式。这个功能后续可以加入，目前因为在写其他功能，加上快过年没有太多时间，全引擎的搜索建议可能要年后才能实现。

**Comment by dinphy** [comment]
谢谢，我把它取消试试
