### ISSUE TITLE
百度的搜索建议 回调地址能不能搞成通用的？自动判断左边选择的搜索引擎

### ISSUE THREAD

**Issue by dinphy** [virzs/Search#2]
```
//回调函数
function callback(data) {
    var str = "";
    for (var i = 0; i < data.s.length; i++) {
        str += `<li><a href=\"https://www.baidu.com/s?wd=${data.s[i]}\">${data.s[i]}</a></li>`;
    }
    searchList.innerHTML = str;
    searchList.style.display = "block";
}
```

> https://www.baidu.com/s?wd=
这一句换成其他搜索引擎，我试了可以用，能否搞成通用的，搜索建议就用百度的

**Comment by virzs** [comment]
这个功能我正在想，看了看其他搜索引擎也有这个功能，当然单独把这一句换成指定搜索引擎的应该也可以，预计下午或者明天吧。

**Comment by dinphy** [comment]
我期待着你

**Comment by dinphy** [comment]
[https://github.com/liumingye/quarkHomePage](https://github.com/liumingye/quarkHomePage)

这个是通用的

**Comment by virzs** [comment]
基础功能已经写好了，剩下的后续再做优化，四个搜索引擎都支持搜索建议，添加新引擎的话需要配置sugurl和jsonp，根据返回的数据可能要再做调整才能正常渲染。
