### ISSUE TITLE
能否增加一个夸克AI搜索引擎，手机端挺好的

### ISSUE THREAD

**Issue by dinphy** [virzs/Search#3]
我尝试了一下，加个搜索选项很简单，就是智能关联提示搞不定，你要是有空，加一个夸克AI搜索引擎

**Comment by virzs** [comment]
这个具体指什么，我这边测试的话是正常的

**Comment by dinphy** [comment]
智能提示的词，有一部分会被输入法挡住，还会和页脚的重合

**Comment by virzs** [comment]
目前计划是以PC端为主，手机端相关功能一般要等到PC端大致优化完成再做
