### ISSUE TITLE
智能联想搜索BUG

### ISSUE THREAD

**Issue by dinphy** [virzs/Search#4]
在移动端几个引擎都可以联想，在pc端只有搜狗引擎会联想，其他的不会

**Comment by virzs** [comment]
The page at 'https://search.virs.xyz/' was loaded over HTTPS, but requested an insecure script 'http://suggestion.baidu.com/su?wd=121&cb=window.baidu.sug'. This request has been blocked; the content must be served over HTTPS.
简单说就是浏览器拒绝了http请求，明天再看咋解决

**Comment by dinphy** [comment]
谢谢，你真给力，我反应的问题你都能回答并解决

**Comment by virzs** [comment]
不客气，毕竟对我来说发现并解决问题是最好的
