### ISSUE TITLE
移动端搜索框优化建议

### ISSUE THREAD

**Issue by dinphy** [virzs/Search#5]
对于移动端给点建议：
可以参考一下360 搜索，点击搜索框后自动跳到顶端，隐藏logo和其他，不搜索就点击取消

**Comment by virzs** [comment]
https://to-do.microsoft.com/sharing?InvitationToken=OFISsz5dSWY0Y2oIdijuAAjJbJE779clb3JENGaue4otGgWnbNY1LqGL4ZUYCJYLU 
 有啥功能/优化/BUG的话可以在这里直接添加，过年这几天不一定有时间

**Comment by dinphy** [comment]
你都会想办法解决的吗

**Comment by virzs** [comment]
不一定，现在的计划已经堆了一堆东西了，你的一些建议我也会考虑加入，但排在前面的东西确实有点多

**Comment by dinphy** [comment]
谢谢你。那些建议都是我个人观点，如果有用你就采纳，也希望没有给你增加麻烦！

**Comment by virzs** [comment]
年后再考虑，你添加的内容我已经看了，优先度要排在后面点
