### ISSUE TITLE
有几个BUG，反馈一下

### ISSUE THREAD

**Issue by dinphy** [virzs/Search#7]
1、IE浏览器直接打不开，加载不出来
2、自定义网址弹窗，取消按钮无效
3、我搬到我用的PHP 环境测试时，第一次能打开，第二次进去就要加载半天，还加载不出来
以上BUG不知道你测试的时候是否存在。

**Comment by virzs** [comment]
1、针对IE浏览器本来是准备仅兼容到IE11，但不知道那个地方没有兼容导致IE浏览器中一直加载，这方面最后在排查
2、自定义网址部分功能还在写，正在考虑改常用网址部分的业务逻辑
3、我对PHP不熟悉，卡在加载的话可以看看控制台什么地方报错了，有错误信息的话方便更正

**Comment by dinphy** [comment]
这是我PHP环境下的地址[https://sou.xwsir.cn/nav/](https://sou.xwsir.cn/nav/)
你可以排查一下，main.js中报错了

**Comment by virzs** [comment]
可能是由于网络问题导致诗词api没有加载完成就加载main.js了
另外，为了防止功能性出现问题我新开了一个dev分支，后续master分支仅会在dev下的代码基本没有错误或功能性完成时才会更新

**Comment by virzs** [comment]
另外，我这里有个QQ群，859791575  有什么问题也可以直接在群里说，不过我有可能会忘记看

**Comment by dinphy** [comment]
加群了。同意下
